#PBS -l walltime=08:00:00
#PBS -l select=1:ncpus=32:mem=64gb

module load anaconda3/personal

source activate mmon-gcm

cd $PBS_O_WORKDIR

run_fva="True"
no_processes=32
output_dir="../outputs/model_solutions/"
model_file="../models/4_stage_GC.xml"
map_file="../inputs/map.json"
parameters_file="../inputs/arabidopsis_parameters.csv"

python ../mmon_gcm/solvemodels.py $run_fva $no_processes $output_dir $model_file $map_file $parameters_file
