#PBS -l walltime=09:00:00
#PBS -l select=1:ncpus=32:mem=128gb

results_path="../outputs/constraint_scan/constraint_scan_results_white.csv"
model_path="../models/4_stage_GC.json"
constraints_csv="../outputs/constraint_scan/constraints_df.csv"
light_colour="white"
no_cores=32

module load anaconda3/personal

source activate mmon-gcm

cd $PBS_O_WORKDIR

python ../mmon_gcm/runconstraintscan.py $results_path $model_path $constraints_csv $light_colour $no_cores
